name: Build kernel by clang-r383902b

on:
  watch:
    types: [started]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4

    - name: Download kernel source
      run: |
        mkdir -p $GITHUB_WORKSPACE/kernel_workspace
        cd $GITHUB_WORKSPACE/kernel_workspace
        git clone https://github.com/wkqnfflz-pixel/KernelSU-Next-Action.git -b main android-kernel --depth=1

    - name: Setup build kernel environment
      run: |
        sudo apt-get update
        sudo apt install -y curl python2 llvm lld wget vim git ccache automake flex lzop bison gperf build-essential zip zlib1g-dev g++-multilib libxml2-utils bzip2 libbz2-dev libbz2-1.0 libghc-bzlib-dev squashfs-tools pngcrush schedtool dpkg-dev liblz4-tool make optipng maven libssl-dev pwgen libswitch-perl policycoreutils minicom libxml-sax-base-perl libxml-simple-perl bc libc6-dev-i386 lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z-dev libgl1-mesa-dev xsltproc unzip device-tree-compiler kmod python3 python3-pip

    - name: Download clang-383902b
      run: |
        cd $GITHUB_WORKSPACE/kernel_workspace
        mkdir clang-aosp
        git clone https://github.com/tomxi1997/Toolchain.git clang-aosp --depth=1

    - name: Build kernel
      run: |
        cd $GITHUB_WORKSPACE/kernel_workspace/android-kernel
        export KBUILD_BUILD_HOST=Github-Action
        export KBUILD_BUILD_USER=$(echo ${{ github.actor }} | tr A-Z a-z)
        export PATH=$GITHUB_WORKSPACE/kernel_workspace/clang-aosp/google_clang/clang-r383902b-11.0.2/bin:$PATH
        
        # [핵심 수정] 저장소 내의 모든 *_defconfig 파일을 찾아 첫 번째 파일을 자동으로 사용합니다.
        CONFIG_FILE=$(find arch/arm64/configs -name "*_defconfig" | head -n 1)
        CONFIG_NAME=$(basename $CONFIG_FILE)
        echo "빌드할 설정 파일: $CONFIG_NAME"
        
        make -j$(nproc --all) O=out ARCH=arm64 CROSS_COMPILE=aarch64-linux-android- CROSS_COMPILE_ARM32=arm-linux-androideabi- $CONFIG_NAME
        make -j$(nproc --all) O=out ARCH=arm64 CROSS_COMPILE=aarch64-linux-android- CROSS_COMPILE_ARM32=arm-linux-androideabi-

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: kernel-build-result
        path: kernel_workspace/android-kernel/out/arch/arm64/boot/Image
